### ISSUE TITLE
Qualifying/lap/finish tracking

### ISSUE THREAD

**Issue by jbhannah** [jbhannah/pitchscore#1]
- [x] Qualifying order button
- [x] Lap/race finish buttons
- [x] Undo/backstep button
- [x] Strikethrough finished players
